### ISSUE TITLE
 No file or variants found for asset: scripts/app.js

### ISSUE THREAD

**Issue by Gagan5278** [icedman/react-qjs-native#1]
Got below error when try to compile app

 No file or variants found for asset: scripts/app.js.

<img width="600" alt="Screenshot 2023-03-09 at 22 41 52" src="https://user-images.githubusercontent.com/2304583/224166834-f36e5b58-f4ae-4bc4-9050-70b78d949776.png">

**Comment by icedman** [comment]
You probably still need to build the react app with yarn build.

**Comment by Gagan5278** [comment]
> You probably still need to build the react app with yarn build.

Let me retry from the beginning. Thanks for your reply. Ill update you.

**Comment by Gagan5278** [comment]
thanks. fixed.
